export const city = [
    "Ho Chi Minh",
    "Hanoi",
    "Danang",
    "An Giang",
    "BA Ria Vung Tau",
    "Bac Giang",
    "Bac Kan",
    "Bac Lieu",
    "Bac Ninh",
    "Ben tre",
    "Binh Duong",
    "Binh Phuoc",
    "Binh Thuan",
    "Pacify",
    "Ca Mau",
    "Can Tho",
    "As tall as",
    "Gia Lai",
    "Ha Giang",
    "Henan",
    "Ha Tinh",
    "Hai Duong",
    "Hai Phong",
    "Hau Giang",
    "Hòa Bình",
    "hung Yen",
    "Khánh Hòa",
    "Kien Giang",
    "Kon Tum",
    "Lai Chau",
    "Lam Dong",
    "Lang Son",
    "Lao Cai",
    "Long An",
    "Nam Dinh",
    "Nghe An",
    "Ninh Binh",
    "Ninh Thuận",
    "Phu-Tho",
    "Phu Yen",
    "Quang Binh",
    "Quang Nam",
    "Quang Ngai",
    "Quang Ninh",
    "Quang Tri",
    "Soc Trang",
    "Son La",
    "Xining",
    "peaceful",
    "Thai Nguyen",
    "Thanh Hoa",
    "Hue",
    "Tien Giang",
    "Tra Vinh",
    "Tuyen Quang",
    "Vinh Long",
    "Vinh Phuc",
    "Yen Bai",
    "Dak Lak",
    "Dak Nong",
    "Dien Bien",
    "Dong Nai",
    "Dong Thap",
];

export const district = [
    "Quận Ba Đình",
    "Quận Hoàn Kiếm",
    "Quận Hai Bà Trưng",
    "Quận Đống Đa",
    "Quận Cầu Giấy",
    "Quận Long Biên",
    "Quận Hoàng Mai",
    "Huyện Sóc Sơn",
    "Quận Bắc Từ Liêm",
    "Huyện Thanh Trì",
    "Huyện Gia Lâm",
    "Huyện Ba Vì",
    "Huyện Chương Mỹ",
    "Huyện Đan Phượng",
    "Huyện Hoài Đức",
    "Huyện Mỹ Đức",
    "Huyện Phú Xuyên",
    "Huyện Phúc Thọ",
    "Huyện Quốc Oai",
    "Huyện Thạch Thất",
    "Huyện Thanh Oai",
    "Huyện Thường Tín",
    "Huyện Ứng Hòa",
    "Huyện Mê Linh",
    "Quận Hà Đông",
    "Thị xã Sơn Tây",
    "Huyện Đông Anh",
    "Quận Nam Từ Liêm",
    "Quận Thanh Xuân",
    "Quận Tây Hồ",
];

export const ward = [
    "Phường Cống Vị",
    "Phường Điện Biên",
    "Phường Đội Cấn",
    "Phường Giảng Võ",
    "Phường Kim Mã",
    "Phường Liễu Giai",
    "Phường Ngọc Hà",
    "Phường Ngọc Khánh",
    "Phường Nguyễn Trung Trực",
    "Phường Phúc Xá",
    "Phường Quán Thánh",
    "Phường Thành Công",
    "Phường Trúc Bạch",
    "Phường Vĩnh Phúc",
];
